name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate and Setup Salesforce CLI
        uses: salesforceaction/setup-sfdx@v2
        with:
          sfdx-auth-url: ${{ secrets.SF_AUTH_URL }}
          destination-org-alias: CICDOrg
          default: true

      - name: Deploy source and run tests
        run: sf project deploy start --source-dir force-app --target-org CICDOrg --test-level RunLocalTests